In [ ]:
#task 1
import numpy as np
n=int(input("length of array:"))
myarr=np.zeros(n,dtype="int")
for i in range(n):
  myarr[i]=int(input())
print("Original Array:" ,myarr)
new=myarr.size+1
myarr2=np.zeros(new,dtype="int")
p=int(input())
for i in range(n):
  myarr2[i]=myarr[i]
  myarr2[-1]=p
print("Resized Array:", myarr2)

length of array:3
5
8
2
Original Array: [5 8 2]
9
Resized Array: [5 8 2 9]


In [ ]:
#task 2
import numpy as np
n=int(input("length of array:"))
myarr=np.zeros(n,dtype="int")
for i in range(n):
  myarr[i]=int(input())
print("Original array: ", myarr)
for i in range(n):
  if myarr[i]<0 or myarr[i]==0:
    myarr[i]=0
  else:
    myarr[i]=1
print("After modifying: ", myarr)

length of array:4
3
4
-2
1
Original array:  [ 3  4 -2  1]
After modifying:  [1 1 0 1]


In [ ]:
#task 3
import numpy as np
def reverseArray(arr):
  arr=arr[::-1]
  return arr

arr1 = np.array([10, 12, 20, 5, 7])
arr1 = reverseArray(arr1)
print(arr1)

[ 7  5 20 12 10]


In [ ]:
#task 4
import numpy as np
def printPairs(arr,n):
  count=0
  for i in range(arr.size):
    for j in range(i+1, arr.size):
      if arr[i]+arr[j]==n:
        count+=1
        print(arr[i], arr[j])
  if count==0:
    print("No pair found")

arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)

7 8
10 5


In [ ]:
#task 5
import numpy as np
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
sum=0
len=vec1.size
for i in range(len):
    sum+= vec1[i]*vec2[i]
print("Dot product:",sum)
if sum%2==0:
 for i in range(0,len,2):
  temp=vec1[i]
  vec1[i]=vec2[i]
  vec2[i]=temp
else:
  for i in range(1,len,2):
    temp=vec1[i]
    vec1[i]=vec2[i]
    vec2[i]=temp
print("After Swapping:")
print(vec1)
print(vec2)

Dot product: 32
After Swapping:
[4 2 6]
[1 5 3]


In [ ]:
#task 6
import numpy as np
n=int(input())
arr1=np.zeros(n,dtype="int")
for i in range(n):
  p=int(input())
  arr1[i]=p
print("Original Array:", arr1)

for i in range(0,n-1):
  minInd=arr1[i]
  swap=arr1[i]
  curr=i
  for j in range(i+1,n):
    if arr1[j]<minInd:
      minInd=arr1[j]
      curr=j
  arr1[i]=minInd
  arr1[curr]=swap
print("Sorted Array:",arr1)

6
3
6
1
2
8
5
Original Array: [3 6 1 2 8 5]
Sorted Array: [1 2 3 5 6 8]


In [ ]:
#task 7
import numpy as np
def flatten(arr1):
  arr2=np.zeros(arr1.size, dtype=arr1.dtype)
  row=arr1.shape[0]
  column=arr1.shape[1]
  k=0
  for i in range(row):
    for j in range(column):
      arr2[k]=arr1[i][j]
      k+=1
  return arr2

arr1 = np.array( [ [1, 2, 3],[3, 4, 5] ] )
arr2 = flatten(arr1)
print(arr2)

[1 2 3 3 4 5]


In [ ]:
#task 8
import numpy as np
arr1 = np.array([ [1, 0, 0, 1],
                  [0, 1, 0, 0],
                  [1, 0, 1, 0],
                  [0, 1, 0, 1] ])

row=arr1.shape[0]
column=arr1.shape[1]
identity=True
for i in range(row):
  for j in range(column):
    if i == j and arr1[i][j] != 1:
        identity=False
        break
    elif i!=j and arr1[i][j] != 0:
        identity=False
        break
  if not identity:
    break

if identity==True:
  print("Identity Matrix")
else:
  print("Not an Identity Matrix")

Not an Identity Matrix


In [ ]:
#task 9
import numpy as np
A = np.array([ [1, 5, 12, 1],
                [2, -4, 6, 7],
                [3, 8, 5, 9],
                [3, 5, 23, -6] ])

row=A.shape[0]
column=A.shape[1]
primarySum=0
secondarySum=0
for i in range(row):
  for j in range(column):
    if i==j:
      primarySum+=A[i][j]
    elif j==row-1:
      secondarySum+=A[i][j]
      row-=1

print(abs(primarySum-secondarySum))

22


In [ ]:
#task 10.1
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

row=A.shape[0]
column=A.shape[1]
arr1=np.zeros((column,row), dtype="int")
for i in range(row):
  for j in range(column):
    arr1[j][i]= A[i][j]
print(arr1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#task 10.2
import numpy as np
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row=arr1.shape[0]
column=arr1.shape[1]
arr2=np.zeros((column, row), dtype="int")
for i in range(row):
  for j in range(column):
    arr2[j][i]= arr1[i][j]

row1=arr2.shape[0]
column1=arr2.shape[1]
arr3=np.zeros((row1,column), dtype="int")

for i in range(row1):
  for j in range(column):
    sum=0
    for p in range(column1):
      sum+=arr2[i][p]*arr1[p][j]
    arr3[i][j]=sum

print(arr3)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [ ]:
#task 11
arr1 = np.array([[4,1,2],
                  [9,3,7]])

row=arr1.shape[0]
column=arr1.shape[1]
difference=abs(row-column)
remainder=difference%row
sum=0
for i in range(row):
  if i==remainder:
    for j in range(column):
      sum+= arr1[i][j]
    average=sum/column
average=round(average,2)

finalArr=np.zeros((row,column), dtype="float")
for i in range(row):
  for j in range(column):
    finalArr[i][j]=arr1[i][j]*average

print(finalArr)

[[25.32  6.33 12.66]
 [56.97 18.99 44.31]]
