In [ ]:
#TASK 1
import numpy as np

class MinHeap():
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__heap = np.array([None]*capacity)
        self.__size = 0

    def get_left_child_index(self, idx):
        return 2 * idx + 1

    def get_right_child_index(self, idx):
        return 2 * idx + 2

    def get_parent_index(self, idx):
        if idx == 0:
            return None
        return (idx - 1)//2


    def extractMin(self):
      if self.__size == 0:
        return "Empty Heap"

      min_value = self.__heap[0]
      self.__heap[0]=self.__heap[self.__size-1]
      self.__heap[self.__size-1]=None
      self.__size -= 1
      self.sink(0)
      return min_value

    def sink(self,idx):
      left= self.get_left_child_index(idx)
      right=self.get_right_child_index(idx)
      small=idx


      if left<self.__size and self.__heap[small]>self.__heap[left]:
        small=left

      if right<self.__size and self.__heap[small]>self.__heap[right]:
        small=right

      if small==idx:
        return

      if small!=idx:
        temp=self.__heap[idx]
        self.__heap[idx]=self.__heap[small]
        self.__heap[small]=temp
        self.sink(small)

    def sort(self):
      b = self.__size
      value = b-1

      while self.__size>0:
        self.__heap[value] = self.extractMin()
        value-=1
      self.__size=b

      for i in range(b//2):
        self.__heap[i],self.__heap[(b - 1)-i]=self.__heap[(b - 1)-i],self.__heap[i]

      return self.__heap[b]

    def insert(self, key):
      if self.__size >= self.__capacity:
        print("No Space Left:", key)
        return
      self.__heap[self.__size] = key
      self.swim(self.__size)
      self.__size += 1

    def swim(self,idx):
      parent=self.get_parent_index(idx)
      if idx==0:
        return

      if parent!=None and self.__heap[idx] <= self.__heap[parent]:
        temp=self.__heap[idx]
        self.__heap[idx]=self.__heap[parent]
        self.__heap[parent]=temp
        self.swim(parent)

    def getheap(self):
      return self.__heap

#DRIVER CODE
arr1= [5,1,2,7,10,11,20]
min=MinHeap(10)

for i in arr1:
  min.insert(i)

print(min.getheap())
min.insert(8)
print(min.getheap())
min.insert(9)
print(f"Full Array: {min.getheap()}")
print(f"Extracted: {min.extractMin()}")
print(min.getheap())
min.sort()
print()
print(f"Final array after sorting:{min.getheap()}")


#final array BST
#        2
#      /  \
#    5     9
#   / \   / \
#  7   10 11  20
# /
# 8

[1 5 2 7 10 11 20 None None None]
[1 5 2 7 10 11 20 8 None None]
Full Array: [1 5 2 7 10 11 20 8 9 None]
Extracted: 1
[2 5 9 7 10 11 20 8 None None]

Final array after sorting:[2 5 7 8 9 10 11 20 None None]


In [ ]:
#TASK 2
import numpy as np

class MaxHeap():
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__heap = np.array([None]*capacity)
        self.__size = 0

    def get_left_child_index(self, idx):
        return 2 * idx + 1

    def get_right_child_index(self, idx):
        return 2 * idx + 2

    def get_parent_index(self, idx):
        if idx == 0:
            return None
        return (idx-1) // 2


    def extractMax(self):
      if self.__size == 0:
        return "Empty Heap"

      max_value = self.__heap[0]
      self.__heap[0]=self.__heap[self.__size-1]
      self.__heap[self.__size-1]= None
      self.__size -= 1
      self.sink(0)
      return max_value

    def sink(self,idx):
      left= self.get_left_child_index(idx)
      right=self.get_right_child_index(idx)
      large=idx


      if left<self.__size and self.__heap[large]<self.__heap[left]:
        large=left

      if right<self.__size and self.__heap[large]<self.__heap[right]:
        large=right

      if large==idx:
        return

      if large!=idx:
        temp=self.__heap[idx]
        self.__heap[idx]=self.__heap[large]
        self.__heap[large]=temp
        self.sink(large)

    def sort(self):
      b = self.__size
      value = b-1

      while self.__size>0:
        self.__heap[value] = self.extractMax()
        value-=1
      self.__size=b

      for i in range(b//2):
        self.__heap[i],self.__heap[(b - 1)-i]=self.__heap[(b - 1)-i],self.__heap[i]

      return self.__heap[b]

    def insert(self, key):
      if self.__size >= self.__capacity:
        print("No Space Left:", key)
        return
      self.__heap[self.__size] = key
      self.swim(self.__size)
      self.__size += 1

    def swim(self,idx):
      parent=self.get_parent_index(idx)
      if idx==0:
        return

      if parent!=None and self.__heap[idx] > self.__heap[parent]:
        temp=self.__heap[idx]
        self.__heap[idx]=self.__heap[parent]
        self.__heap[parent]=temp
        self.swim(parent)

    def getheap(self):
      return self.__heap

#DRIVER CODE
arr2= [5,1,2,7,10,11,20]
max=MaxHeap(10)

for i in arr1:
  max.insert(i)

print(max.getheap())
max.insert(8)
print(max.getheap())
max.insert(9)
print(f"Full Array: {max.getheap()}")
print(f"Extracted: {max.extractMax()}")
print(max.getheap())
max.sort()
print()
print(f"Final array after sorting:{max.getheap()}")

#final array BST
#       11
#      /  \
#    9     10
#   / \   / \
#  8   5 2   7
# /
# 1

[20 7 11 1 5 2 10 None None None]
[20 8 11 7 5 2 10 1 None None]
Full Array: [20 9 11 8 5 2 10 1 7 None]
Extracted: 20
[11 9 10 8 5 2 7 1 None None]

Final array after sorting:[11 10 9 8 7 5 2 1 None None]


In [ ]:
#TASK 3
def loads(self,m):
  min=MinHeap(m)
  size=len(self)

  for i in range(size):
    if i>=m:
      a=min.extractMin()
      b=a+self[i]
      min.insert(b)
    else:
      min.insert(self[i])

  return min.getheap()


#DRIVER CODE
tasks = [2, 4, 7, 1, 6]
m = 4
print(loads(tasks,m))

[2 4 7 7]


In [ ]:
# TASK 3 THIS SHOULDVE WORKED BUT KAAJ KORENA FOR SOME REASON

def loads(tasks, m):
    machine_heap = MinHeap(m)
    size=len(tasks)
    for i in range(m):
        machine_heap.insert(0)

    for task in tasks:
      if size>m:
        min_load = machine_heap.extractMin()
        updated_load = min_load + task
        machine_heap.insert(updated_load)

    return machine_heap.getheap()

#DRIVER CODE
tasks = [2, 4, 7, 1, 6]
m = 4
print(loads(tasks,m))

[2 7 4 7]


In [ ]:
#TASK 4
def maxExt(self,k):
  maxheap=MaxHeap(len(self))
  s=np.array([None]*k)
  size=len(self)

  for i in range(size):
    maxheap.insert(self[i])

  for i in range(len(s)):
    a=maxheap.extractMax()
    s[i]=a

  return s

#DRIVER CODE
nums = [4, 10, 2, 8, 6, 7]
k = 3
print(maxExt(nums,k))

[10 8 7]
