In [ ]:
#alternative code of task 1

#Adjacency matrix for Undirected Unweighted Graph
import numpy as np
class Graph:
    def __init__(self, num_vertices):
        self.size = len(num_vertices)
        self.num_vertices = num_vertices
        self.adj_matrix = np.zeros((self.size,self.size), dtype=int)
        self.vertex_index = {}
        self.maxvertex=None
        for i in range(self.size):
          self.vertex_index[num_vertices[i]] = i

    def add_edges(self, i, j):
        m = self.vertex_index[i]
        n = self.vertex_index[j]
        self.adj_matrix[m][n] = 1
        self.adj_matrix[n][m] = 1

    def print_matrix(self):
        print("Adjcaency Matrix:")
        for row in self.adj_matrix:
            print(row)

    def get_degree(self, num_vertices):
        u = self.vertex_index[num_vertices]
        degree = 0
        for k in range(self.size):
            if u==k:
              continue
            if self.adj_matrix[u][k] != 0:
                degree += 1
        return degree

    def max_degree_matrix(self):
      max=0
      vertex=None
      for i in self.num_vertices:
        degree_count= self.get_degree(i)
        if degree_count> max:
          max=degree_count
          self.maxvertex=i
      return (max,self.maxvertex)



#Adjacency list for Undirected Unweighted graph
class Edge:
    def __init__(self, source, destination, next_node=None):
        self.source = source
        self.destination = destination
        self.next = next_node

class AdjacencyListGraph:
    def __init__(self, num_vertices):
        self.num_vertices = num_vertices
        self.size = len(num_vertices)
        self.adj_list = [None] * self.size
        self.vertex_index = {}
        for i in range(len(num_vertices)):
          self.vertex_index[num_vertices[i]] = i
        self.maxvertex=None


    def add_edges(self, edges):
        for source, destination in edges:
            self.add_edge(source, destination)
            self.add_edge(destination, source)

    def add_edge(self, source, destination):
        new_edge = Edge(source, destination)
        new_edge.next = self.adj_list[self.vertex_index[source]]
        self.adj_list[self.vertex_index[source]] = new_edge

    def print_list(self):
        print("Adjacency List:")
        for i in range(self.size):
            print(f"{i}: ", end="")
            current = self.adj_list[i]
            while current:
                print(f"{current.destination}", end=" ")
                current = current.next
            print()

    def get_degree(self, num_vertices):
        a = self.vertex_index[num_vertices]
        degree = 0
        current = self.adj_list[a]
        while current!=None:
            degree += 1
            current = current.next
        return degree

    def max_degree_list(self):
      max=0
      for i in self.num_vertices:
        degree_count= self.get_degree(i)
        if degree_count> max:
          max=degree_count
          self.maxvertex=i
      return (max,self.maxvertex)



#Driver Code
demo = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
matrix_Graph= Graph(demo)
list_Graph= AdjacencyListGraph(demo)

number_of_edges=[('A', 'B'), ('A', 'C'),  ('A', 'G'),
                  ('B', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'D'),
                  ('C', 'F'), ('D', 'E'), ('D', 'G'),
                  ('E', 'G'), ('F', 'G'), ('B', 'F')]

for i,j in number_of_edges:
  matrix_Graph.add_edges(i,j)
  list_Graph.add_edges([(i,j)])

print("For Matrix---")
print("Vertex:", matrix_Graph.max_degree_matrix()[1] )
print("Degree:", matrix_Graph.max_degree_matrix()[0])
print()

print("For List---")
print("Vertex:", list_Graph.max_degree_list()[1])
print("Degree:", list_Graph.max_degree_list()[0])

For Matrix---
Vertex: B
Degree: 5

For List---
Vertex: B
Degree: 5


In [ ]:
#matirx function
import numpy as np
class Graph:
    def __init__(self, num_vertices,directed=False):
        self.size = len(num_vertices)
        self.num_vertices = num_vertices
        self.adj_matrix = np.zeros((self.size,self.size), dtype=int)
        self.vertex_index = {}
        self.directed=directed
        self.maxvertex=None
        for i in range(self.size):
          self.vertex_index[num_vertices[i]] = i

    def add_edges(self, i, j, k=1):
        m = self.vertex_index[i]
        n = self.vertex_index[j]
        self.adj_matrix[m][n] = k
        if self.directed==False:
          self.adj_matrix[n][m] = k


    def print_matrix(self):
        print("Adjcaency Matrix:")
        for row in self.adj_matrix:
            print(row)

    def get_degree(self, num_vertices):
        u = self.vertex_index[num_vertices]
        degree = 0
        for k in range(self.size):
            if u==k:
              continue
            if self.adj_matrix[u][k] != 0:
                degree += 1
        return degree

    def get_weight_matrix(self, num_vertices):
        u = self.vertex_index[num_vertices]
        totalweight = 0
        for k in range(self.size):
          if u==k:
            continue
          if self.adj_matrix[u][k] != 0:
            totalweight += self.adj_matrix[u][k]
        return totalweight

In [ ]:
#list function
class WEdge:
    def __init__(self, source, destination, weight, next_node=None):
        self.source = source
        self.destination = destination
        self.weight = weight
        self.next = next_node

class AdjacencyListGraph:
    def __init__(self, num_vertices, directed=False):
        self.num_vertices = num_vertices
        self.size = len(num_vertices)
        self.directed= directed
        self.adj_list = [None] * self.size
        self.vertex_index = {}
        for i in range(len(num_vertices)):
          self.vertex_index[num_vertices[i]] = i
        self.maxvertex=None


    def add_edges(self, edges):
        for source, destination, weight in edges:
            self.add_edge(source, destination, weight)
            if self.directed==False:
              self.add_edge(destination, source, weight)

    def add_edge(self, source, destination, weight=None):
        a=self.vertex_index[source]
        new_edge = WEdge(source, destination, weight)
        new_edge.next = self.adj_list[a]
        self.adj_list[a] = new_edge


    def print_list(self):
        print("Adjacency List:")
        for i in range(self.size):
            print(f"{i}: ", end="")
            current = self.adj_list[i]
            while current:
                print(f"{current.destination}", end=" ")
                current = current.next
            print()

    def get_degree(self, num_vertices):
        a = self.vertex_index[num_vertices]
        degree = 0
        current = self.adj_list[a]
        while current!=None:
            degree += 1
            current = current.next
        return degree

    def get_weight_list(self, num_vertices):
        a = self.vertex_index[num_vertices]
        totalweight = 0
        current = self.adj_list[a]
        while current!=None:
          totalweight  += current.weight
          current = current.next
        return totalweight

In [ ]:
#TASK1
def max_degree_list(self):
      max=0
      for i in self.num_vertices:
        degree_count= self.get_degree(i)
        if degree_count> max:
          max=degree_count
          maxvertex=i
      return (max,maxvertex)

def max_degree_matrix(self):
      max=0
      vertex=None
      for i in self.num_vertices:
        degree_count= self.get_degree(i)
        if degree_count> max:
          max=degree_count
          maxvertex=i
      return (max,maxvertex)



#Driver Code
demo = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
matrix_Graph= Graph(demo)
list_Graph= AdjacencyListGraph(demo)

number_of_edges=[('A', 'B', 0), ('A', 'C', 0),  ('A', 'G', 0),
                  ('B', 'C', 0), ('B', 'D', 0), ('B', 'E', 0), ('C', 'D', 0),
                  ('C', 'F', 0), ('D', 'E', 0), ('D', 'G', 0),
                  ('E', 'G', 0), ('F', 'G', 0), ('B', 'F', 0)]

for i,j,k in number_of_edges:
  matrix_Graph.add_edges(i,j)
  list_Graph.add_edges([(i,j,k)])


print("For Matrix---")
print("Vertex:", max_degree_matrix(matrix_Graph)[1] )
print("Degree:", max_degree_matrix(matrix_Graph)[0])
print()

print("For List---")
print("Vertex:", max_degree_list(list_Graph)[1])
print("Degree:", max_degree_list(list_Graph)[0])

For Matrix---
Vertex: B
Degree: 5

For List---
Vertex: B
Degree: 5


In [ ]:
#TASK 2
def max_weight_list(self):
      max=0
      for i in self.num_vertices:
        weight= self.get_weight_list(i)
        if weight> max:
          max=weight
          maxvertex=i
      return (max,maxvertex)

def max_weight_matrix(self):
      max=0
      for i in self.num_vertices:
        count= self.get_weight_matrix(i)
        if count> max:
          max=count
          maxvertex=i
      return (max,maxvertex)


#Driver Code
demo = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
matrix_Graph= Graph(demo)
list_Graph= AdjacencyListGraph(demo)

number_of_edges=[('A', 'B', 1), ('A', 'C', 1),  ('A', 'G', 1),
                  ('B', 'C', 1), ('B', 'D', 2), ('B', 'E', 2), ('C', 'D', 5),
                  ('C', 'F', 2), ('D', 'E', 4), ('D', 'G', 3),
                  ('E', 'G', 1), ('F', 'G', 1), ('B', 'F', 3)]

for i,j,k in number_of_edges:
  matrix_Graph.add_edges(i,j,k)
  list_Graph.add_edges([(i,j,k)])

print("For Matrix---")
print("Vertex:", max_weight_matrix(matrix_Graph)[1] )
print("Weight:", max_weight_matrix(matrix_Graph)[0])
print()

print("For List---")
print("Vertex:", max_weight_list(list_Graph)[1])
print("Weight:", max_weight_list(list_Graph)[0])

For Matrix---
Vertex: D
Weight: 14

For List---
Vertex: D
Weight: 14


In [ ]:
#TASK 3
def max_weight_list(self):
      max=0
      for i in self.num_vertices:
        weight= self.get_weight_list(i)
        if weight> max:
          max=weight
          maxvertex=i
      return (max,maxvertex)

def max_weight_matrix(self):
      max=0
      for i in self.num_vertices:
        count= self.get_weight_matrix(i)
        if count> max:
          max=count
          maxvertex=i
      return (max,maxvertex)

def max_degree_list(self):
      max=0
      for i in self.num_vertices:
        degree_count= self.get_degree(i)
        if degree_count> max:
          max=degree_count
          maxvertex=i
      return (max,maxvertex)

def max_degree_matrix(self):
      max=0
      vertex=None
      for i in self.num_vertices:
        degree_count= self.get_degree(i)
        if degree_count> max:
          max=degree_count
          maxvertex=i
      return (max,maxvertex)


#Driver Code
demo = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
matrix_Graph= Graph(demo,True)
list_Graph= AdjacencyListGraph(demo,True)

number_of_edges=[('A', 'B', 1), ('A', 'C', 1),  ('A', 'G', 1),
                  ('B', 'C', 1), ('B', 'D', 2), ('B', 'E', 2), ('C', 'D', 5),
                  ('C', 'F', 2), ('D', 'E', 4), ('D', 'G', 3),
                  ('E', 'G', 1), ('F', 'G', 1), ('B', 'F', 3)]

for i,j,k in number_of_edges:
  matrix_Graph.add_edges(i,j,k)
  list_Graph.add_edges([(i,j,k)])

print("FOR DIRECTED WEIGHTED GRAPH")
print()
print("For Matrix---")
print("Vertex:", max_weight_matrix(matrix_Graph)[1] )
print("Weight:", max_weight_matrix(matrix_Graph)[0])
print("Degree:", max_degree_matrix(matrix_Graph)[0])

print()

print("For List---")
print("Vertex:", max_weight_list(list_Graph)[1])
print("Weight:", max_weight_list(list_Graph)[0])
print("Degree:", max_degree_list(list_Graph)[0])

FOR DIRECTED WEIGHTED GRAPH

For Matrix---
Vertex: B
Weight: 8
Degree: 4

For List---
Vertex: B
Weight: 8
Degree: 4


In [ ]:
#TASK4
def convert_undirected_list(self):
  for i in range(self.size):
    current = self.adj_list[i]
    while current!=None:
      a,b,c=current.source, current.destination, current.weight
      reverse = self.vertex_index[b]
      reverseCurrent = self.adj_list[reverse]
      directed=False
      while reverseCurrent!=None:
        if reverseCurrent.destination==a:
          directed=True
          break
        reverseCurrent=reverseCurrent.next

      if directed==False:
        self.add_edge(b, a, c)
      current= current.next
  self.directed = False

def convert_undirected_matrix(self):
  if self.directed==True:
    for i in range(self.size):
      for j in range(self.size):
        if self.adj_matrix[i][j] != 0:
          self.adj_matrix[j][i] = self.adj_matrix[i][j]
  self.directed = False


#Driver Code
demo = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
matrix_Graph= Graph(demo,True)
list_Graph= AdjacencyListGraph(demo,True)

number_of_edges=[('A', 'B', 1), ('A', 'C', 1),  ('A', 'G', 1),
                  ('B', 'C', 1), ('B', 'D', 2), ('B', 'E', 2), ('C', 'D', 5),
                  ('C', 'F', 2), ('D', 'E', 4), ('D', 'G', 3),
                  ('E', 'G', 1), ('F', 'G', 1), ('B', 'F', 3)]

for i,j,k in number_of_edges:
  matrix_Graph.add_edges(i,j,k)
  list_Graph.add_edges([(i,j,k)])

print("For Matrix---")
convert_undirected_matrix(matrix_Graph)
matrix_Graph.print_matrix()

print()

print("For List---")
convert_undirected_list(list_Graph)
list_Graph.print_list()

For Matrix---
Adjcaency Matrix:
[0 1 1 0 0 0 1]
[1 0 1 2 2 3 0]
[1 1 0 5 0 2 0]
[0 2 5 0 4 0 3]
[0 2 0 4 0 0 1]
[0 3 2 0 0 0 1]
[1 0 0 3 1 1 0]

For List---
Adjacency List:
0: G C B 
1: A F E D C 
2: B A F D 
3: C B G E 
4: D B G 
5: C B G 
6: F E D A 
